### ISSUE TITLE
tar archives contain no data

### ISSUE THREAD

**Issue by tillrobin** [trajkovski-lab/CMMG#3]
Hi,
the files https://ezmeta.unige.ch/CMMG/representative_genomes.tar.gz and https://ezmeta.unige.ch/CMMG/all_genomes.tar.gz contain only symbolic links not the real genome data. Please upload the full data.

Best Till Robin

**Comment by SilasK** [comment]
A tar archive full of symlinks is not very useful, haha. I uploaded the representatives. The rest is compressing. 
Keep in mind to drop the iMGMC/mMAG genomes not to include them twice. 

Will you also be present on the zoom call next Tuesday?

**Comment by SilasK** [comment]
I put all genomes online
